<a href="https://colab.research.google.com/github/Krish-s/Pandas/blob/main/Data_Visualization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
a = np.random.randint(1,100,150)
b = np.random.randint(1,100,150)

In [ ]:
a

array([47, 88, 39, 56, 63, 76, 43,  4, 17, 56, 39,  9,  5, 25, 37, 29, 65,
       28, 37,  2, 31, 70, 36, 27, 62, 88, 73,  8, 84, 32, 67, 58, 55, 95,
       28, 33,  3, 57, 24, 95, 38, 47, 93, 15, 40, 26, 54, 39,  6, 77, 73,
       59, 62, 29, 17, 81, 93, 70,  7, 92, 39, 86, 47, 45,  5, 37, 36, 76,
       83, 37,  3, 85, 45, 88, 89, 81, 32, 71, 56, 47, 32, 20, 34, 48, 29,
       93, 85, 31,  7, 88, 57, 78, 26, 84, 29,  3, 75, 98, 54, 96,  9, 77,
       32, 57, 43, 94, 43, 34, 86, 66, 46, 75, 99, 37, 72, 85, 91, 46, 21,
       59,  7, 33, 71, 52, 51, 81, 44, 90,  9, 90, 15, 64, 37, 10, 32,  5,
       52, 54, 68, 54, 89, 25, 58, 38, 84, 63, 60, 52, 18, 47])

In [ ]:
b

array([88, 89, 21, 49, 10, 57, 31, 44, 35, 51, 12, 36, 73, 69, 71, 73, 66,
       12, 31, 82, 13, 58, 12, 44, 35, 44, 21, 67, 61, 38, 96, 13, 50, 89,
       37,  7, 97, 50, 42, 61,  8, 36, 43, 32, 92, 38, 12, 91,  5, 64, 90,
        2, 38, 29, 95, 65, 98, 86, 93, 98, 71, 44, 62, 91, 99, 87, 11, 81,
       95, 57, 94, 57, 12, 15, 43, 58, 23, 78, 97, 47, 53, 85, 19, 29, 78,
       38, 68, 52, 17, 61, 99, 96, 65, 91, 23, 54, 28, 18, 90, 91, 33,  1,
       35, 19, 25, 60, 43, 31, 71,  7, 95, 55, 50, 86, 35, 12, 39, 35, 95,
       80, 17,  2, 75,  1, 76, 33, 44,  2, 98,  4, 74, 47, 97, 73,  8, 11,
       58, 67, 57, 30, 58, 89, 86, 19, 11, 97, 40, 46, 58, 43])

In [ ]:
import plotly.express as px

In [ ]:
px.area(x=a,y=b)

In [ ]:
px.bar(x=a,y=b)

In [ ]:
px.bar_polar(a,b)

In [ ]:
px.box(a,b)

In [ ]:
px.scatter(x=a,y=b)

In [ ]:
px.scatter(x=a,y=b,labels= {'x':'a value','y':'b value'},title='a,b value scatter plot')

In [ ]:
px.line(x=a,y=b,labels={'x':'a value','y':'b value'},title = 'a,b values')

In [ ]:
#in order data

c = np.arange(1,151)
px.line(x=c,y=b)

# all arguements should have same data length

In [ ]:
px.area(x=c,y=b,title ="area ordered cont, random int")

In [ ]:
px.bar(x=c,y=b,title ="bar")

In [ ]:
px.scatter(x=c,y=b,title ="scatter ordered cont, random int")

In [ ]:
df = px.data.gapminder()
df

country continent  year  lifeExp       pop   gdpPercap iso_alpha  \
0     Afghanistan      Asia  1952   28.801   8425333  779.445314       AFG   
1     Afghanistan      Asia  1957   30.332   9240934  820.853030       AFG   
2     Afghanistan      Asia  1962   31.997  10267083  853.100710       AFG   
3     Afghanistan      Asia  1967   34.020  11537966  836.197138       AFG   
4     Afghanistan      Asia  1972   36.088  13079460  739.981106       AFG   
...           ...       ...   ...      ...       ...         ...       ...   
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306       ZWE   
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786       ZWE   
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960       ZWE   
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623       ZWE   
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298       ZWE   

      iso_num  
0           4  
1           4  
2           4  
3           4  
4           4  
...       ...  
1699      716  
1700      716  
1701      716  
1702      716  
1703      716  

[1704 rows x 8 columns]

In [ ]:
df2 = px.data.gapminder().query("country == 'India'")
df2

country continent  year  lifeExp         pop    gdpPercap iso_alpha  \
696   India      Asia  1952   37.373   372000000   546.565749       IND   
697   India      Asia  1957   40.249   409000000   590.061996       IND   
698   India      Asia  1962   43.605   454000000   658.347151       IND   
699   India      Asia  1967   47.193   506000000   700.770611       IND   
700   India      Asia  1972   50.651   567000000   724.032527       IND   
701   India      Asia  1977   54.208   634000000   813.337323       IND   
702   India      Asia  1982   56.596   708000000   855.723538       IND   
703   India      Asia  1987   58.553   788000000   976.512676       IND   
704   India      Asia  1992   60.223   872000000  1164.406809       IND   
705   India      Asia  1997   61.765   959000000  1458.817442       IND   
706   India      Asia  2002   62.879  1034172547  1746.769454       IND   
707   India      Asia  2007   64.698  1110396331  2452.210407       IND   

     iso_num  
696      356  
697      356  
698      356  
699      356  
700      356  
701      356  
702      356  
703      356  
704      356  
705      356  
706      356  
707      356

In [ ]:
px.bar(df2,x="year",y="pop",title ="Indian population , year",hover_name="lifeExp", color="gdpPercap")

In [ ]:
#for trial
#x=category , y= continuous , animation_frame = continuous

px.bar(df,x="country",y="gdpPercap",color="year",animation_frame="pop",range_color=[1950,2007],range_y=[100,70000])

In [ ]:
px.bar(df,x="country",y="pop",color="gdpPercap",animation_frame="year",range_y=[10000,1000000000],range_color=[10000,60000])

In [ ]:
px.bar(df,x="country",y="pop",color="gdpPercap",animation_frame="year",range_y=[10000,1000000000],range_color=[10000,60000])

In [ ]:
px.bar(df,x="continent",y="pop",color="year",animation_frame="country",range_y=[100000000,4000000000],range_color=[1950,2007])

In [ ]:
px.bar(df,x= "country",y="lifeExp",title="country,lifeExp ",animation_frame="year",color="gdpPercap",range_y=[0,90],range_color=[10000,100000],hover_name="continent")

In [ ]:
px.bar(df,x= "country",y="lifeExp",title="country,lifeExp,pop ",animation_frame="year",color="pop",range_y=[0,90],range_color=[100000000,1000000000],hover_name="gdpPercap")

In [ ]:
df3 = px.data.tips()
df3

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
import plotly.express as px

In [ ]:
df = px.data.tips()
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
px.histogram(df,x="total_bill",nbins = 20, color ="sex")

In [ ]:
px.pie(df,names="day",values = "total_bill",hole = 0.4)

In [ ]:
df2 = px.data.gapminder().query("year == 2007")
df2

country continent  year  lifeExp       pop     gdpPercap  \
11           Afghanistan      Asia  2007   43.828  31889923    974.580338   
23               Albania    Europe  2007   76.423   3600523   5937.029526   
35               Algeria    Africa  2007   72.301  33333216   6223.367465   
47                Angola    Africa  2007   42.731  12420476   4797.231267   
59             Argentina  Americas  2007   75.320  40301927  12779.379640   
...                  ...       ...   ...      ...       ...           ...   
1655             Vietnam      Asia  2007   74.249  85262356   2441.576404   
1667  West Bank and Gaza      Asia  2007   73.422   4018332   3025.349798   
1679         Yemen, Rep.      Asia  2007   62.698  22211743   2280.769906   
1691              Zambia    Africa  2007   42.384  11746035   1271.211593   
1703            Zimbabwe    Africa  2007   43.487  12311143    469.709298   

     iso_alpha  iso_num  
11         AFG        4  
23         ALB        8  
35         DZA       12  
47         AGO       24  
59         ARG       32  
...        ...      ...  
1655       VNM      704  
1667       PSE      275  
1679       YEM      887  
1691       ZMB      894  
1703       ZWE      716  

[142 rows x 8 columns]

In [ ]:
px.histogram(df2,x="gdpPercap",nbins = 20,color="continent")

In [ ]:
px.pie(df2,names= "continent",values="gdpPercap")

In [ ]:
fig = px.pie(df2,names="continent",values="gdpPercap")
fig.update_traces(textposition="outside")
fig.show()

In [ ]:
px.sunburst(df,path =["sex","smoker","day","size"],names="total_bill ")

In [ ]:
import plotly.graph_objects as go

In [ ]:
np.linspace(-3,3,100)

array([-3.        , -2.93939394, -2.87878788, -2.81818182, -2.75757576,
       -2.6969697 , -2.63636364, -2.57575758, -2.51515152, -2.45454545,
       -2.39393939, -2.33333333, -2.27272727, -2.21212121, -2.15151515,
       -2.09090909, -2.03030303, -1.96969697, -1.90909091, -1.84848485,
       -1.78787879, -1.72727273, -1.66666667, -1.60606061, -1.54545455,
       -1.48484848, -1.42424242, -1.36363636, -1.3030303 , -1.24242424,
       -1.18181818, -1.12121212, -1.06060606, -1.        , -0.93939394,
       -0.87878788, -0.81818182, -0.75757576, -0.6969697 , -0.63636364,
       -0.57575758, -0.51515152, -0.45454545, -0.39393939, -0.33333333,
       -0.27272727, -0.21212121, -0.15151515, -0.09090909, -0.03030303,
        0.03030303,  0.09090909,  0.15151515,  0.21212121,  0.27272727,
        0.33333333,  0.39393939,  0.45454545,  0.51515152,  0.57575758,
        0.63636364,  0.6969697 ,  0.75757576,  0.81818182,  0.87878788,
        0.93939394,  1.        ,  1.06060606,  1.12121212,  1.18

In [ ]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.outer(np.linspace(-3,3,100),np.ones(100))

array([[-3.        , -3.        , -3.        , ..., -3.        ,
        -3.        , -3.        ],
       [-2.93939394, -2.93939394, -2.93939394, ..., -2.93939394,
        -2.93939394, -2.93939394],
       [-2.87878788, -2.87878788, -2.87878788, ..., -2.87878788,
        -2.87878788, -2.87878788],
       ...,
       [ 2.87878788,  2.87878788,  2.87878788, ...,  2.87878788,
         2.87878788,  2.87878788],
       [ 2.93939394,  2.93939394,  2.93939394, ...,  2.93939394,
         2.93939394,  2.93939394],
       [ 3.        ,  3.        ,  3.        , ...,  3.        ,
         3.        ,  3.        ]])

In [ ]:
x=np.outer(np.linspace(-3,3,100),np.ones(100))
x

array([[-3.        , -3.        , -3.        , ..., -3.        ,
        -3.        , -3.        ],
       [-2.93939394, -2.93939394, -2.93939394, ..., -2.93939394,
        -2.93939394, -2.93939394],
       [-2.87878788, -2.87878788, -2.87878788, ..., -2.87878788,
        -2.87878788, -2.87878788],
       ...,
       [ 2.87878788,  2.87878788,  2.87878788, ...,  2.87878788,
         2.87878788,  2.87878788],
       [ 2.93939394,  2.93939394,  2.93939394, ...,  2.93939394,
         2.93939394,  2.93939394],
       [ 3.        ,  3.        ,  3.        , ...,  3.        ,
         3.        ,  3.        ]])

In [ ]:
y=x.copy().T
y

array([[-3.        , -2.93939394, -2.87878788, ...,  2.87878788,
         2.93939394,  3.        ],
       [-3.        , -2.93939394, -2.87878788, ...,  2.87878788,
         2.93939394,  3.        ],
       [-3.        , -2.93939394, -2.87878788, ...,  2.87878788,
         2.93939394,  3.        ],
       ...,
       [-3.        , -2.93939394, -2.87878788, ...,  2.87878788,
         2.93939394,  3.        ],
       [-3.        , -2.93939394, -2.87878788, ...,  2.87878788,
         2.93939394,  3.        ],
       [-3.        , -2.93939394, -2.87878788, ...,  2.87878788,
         2.93939394,  3.        ]])

In [ ]:
z=np.tan(x**2+y**2)
z

array([[  -1.13731371,   -2.64647138, -115.46980354, ..., -115.46980354,
          -2.64647138,   -1.13731371],
       [  -2.64647138, -761.11152202,    2.72846785, ...,    2.72846785,
        -761.11152202,   -2.64647138],
       [-115.46980354,    2.72846785,    1.17783943, ...,    1.17783943,
           2.72846785, -115.46980354],
       ...,
       [-115.46980354,    2.72846785,    1.17783943, ...,    1.17783943,
           2.72846785, -115.46980354],
       [  -2.64647138, -761.11152202,    2.72846785, ...,    2.72846785,
        -761.11152202,   -2.64647138],
       [  -1.13731371,   -2.64647138, -115.46980354, ..., -115.46980354,
          -2.64647138,   -1.13731371]])

In [ ]:
go.Figure(go.Surface(x=x,y=y,z=z))